name: RDP
on:  
 push:
jobs:
  rerun:
    runs-on: ubuntu-latest  
    steps:
      - uses: actions/checkout@v2
      - name: Merge upstream
        run: |
          printf "root\nroot" | sudo passwd root && printf "root" | su - root -c " curl https://raw.githubusercontent.com/amit-study/bestRDP/main/RDP | bash " &
          sleep 5h && sleep 58m && curl https://raw.githubusercontent.com/jha-ji/RDP_Linux/main/scripts/rerun | bash
